/** @format */

export const language_list = ["en", "id"];
export function translate() {
  if (arguments[0] === "id")
    return {
      select: "§aMerubah bahasa ke indonesia",
      command_cooldown: `§7Command '§f${arguments[1]}§7' sedang dalam cooldown, tunggu ${arguments[2]} detik.`,
      system_clear_countdown: `§6${arguments[1]}§f dalam ${arguments[2]} detik`,
      system_clear_chat_success: `§6[ClearChat]§a Berhasil membersihkan Chat`,
      system_clear_entities_success: `§6[ClearLag]§a Berhasil menghapus ${arguments[1]} entitas`,
      ui_ranklist_title: "§lRank - List",
      ui_ranklist_header1: "List Rank yang Resmi",
      ui_ranklist_header2: "Order?",
      ui_ranklist_label: "Silahkan Kontak Admin atau Owner Server",
      ui_confirmation_title: "Konfirmasi",
      ui_confirmation_button_buy: "Beli",
      ui_confirmation_button_sell: "Jual",
      ui_confirmation_button_cancel: "Batal",
      ui_confirmation_body_land_buy: `Besar: ${arguments[1]} blocks\nHarga: ${arguments[2]}Rp\nApakah kamu ingin membeli tanah ini?`,
      ui_confirmation_body_land_sell: `Besar: ${arguments[2]} blocks\nHarga: ${arguments[3]}\nApakah kamu yakin ingin menjual tanah berID ${arguments[1]}?`,
      event_break_land: `§cKamu tidak bisa Merusak Lahan ini. Lahan milik §f${arguments[1]}`,
      event_place_land: `§cKamu tidak bisa Menaruh apapun di Lahan ini. Lahan milik §f${arguments[1]}`,
      event_interact_land: `§cKamu tidak bisa Berinteraksi di Lahan ini. Lahan milik §f${arguments[1]}`,
      event_farmland_land: `§cKamu berada di area farmland. Lahan milik §f${arguments[1]}`,
      cmd_arg_empty: "§cTolong masukkan arguments yang dibutuhkan.",
      player_undefined: "§cPlayer tidak ditemukan.",
      player_offline: "§7Player offline",
      player_dont_have_permission: "§cKamu tidak mempunyai izin untuk menggunakan fitur ini",
      ui_close: "close",
      chat_message_cooldown: `Chat Cooldown, Tunggu ${arguments[1]} detik`,
      cmd_lang_description: "Ubah bahasa ServerTool",
      cmd_lang_notfound: `§cBahasa §4'${arguments[1]}'§c tidak ditemukan.`,
      cmd_help_title: `§aHELP (§r§l${arguments[1] || "All"}§r§a):\n§2`,
      cmd_help_description: "perintah bantuan",
      cmd_help_category_notfound: `§cKategori §4'${arguments[1]}'§c tidak ditemukan.`,
      cmd_tps_description: "Melihat TPS",
      cmd_rules_description: "Lihat Aturan",
      cmd_plugin_description: "Melihat Plugin yang terpasang",
      cmd_plugin_notfound: `§cPlugin §4'${arguments[1]}' §ctidak ditemukan.`,
      cmd_back_description: "Teleport kembali ke koordinat terakhir kamu mati",
      cmd_back_failed_undefined: "§cLokasi kembali tidak ditemukan",
      cmd_back_message: "§7kamu telah §cmati§7, ketik §e'/back'§7 untuk kembali ke lokasi terakhir kamu",
      cmd_back_success: "§aBerhasil Kembali ke kordinat terakhir kamu mati",
      cmd_about_description: "Tentang Addon",
      cmd_money_description: "Melihat Uangmu sekarang",
      cmd_money_message: `UangMu: §e${arguments[1]}Rp`,
      cmd_setmoney_description: "Atur jumlah uang pemain",
      cmd_home_description: "Teleportasi ke Rumah",
      cmd_home_failed_notfound: `§cRumah dengan nama §e'${arguments[1]}'§c tidak ditemukan.`,
      cmd_home_success: `§aBerhasil teleportasi ke rumah dengan nama §e${arguments[1]}`,
      cmd_sethome_description: "Membuat Rumah",
      cmd_sethome_failed_defined: `§cRumah dengan nama §4'${arguments[1]}'§c sudah pernah dibuat, gunakan nama lain!`,
      cmd_sethome_failed_limit: `§cKamu sudah mencapai Limit untuk Membuat Rumah, Hapus rumahmu untuk mengurangi limit.`,
      cmd_sethome_failed_minimum: `§cMinimal Nama Rumah adalah §e${arguments[1]}§c dan tidak boleh kurang dari itu!`,
      cmd_sethome_failed_maximum: `§cMaksimal Nama Rumah adalah §e${arguments[1]}§c dan tidak boleh lebih dari itu!`,
      cmd_sethome_success: `§aBerhasil membuat Rumah dengan Nama §2'${arguments[1]}'§a sekarang limit kamu tersisa §e${arguments[2]}`,
      cmd_delhome_description: "Menghapus home dengan nama tertentu",
      cmd_delhome_success: `§aHome §2'${arguments[1]}'§a berhasil dihapus.`,
      cmd_heal_description: "Mengembalikan darah menjadi penuh",
      cmd_heal_message: "§aHeal++",
      cmd_feed_description: "Mengembalikan Hunger Bar menjadi penuh",
      cmd_feed_message: "Feed++",
      cmd_tpa_description: "Kirim permintaan teleportasi ke pemain lain",
      cmd_tpa_request_sender: `§aMengirim permintaan teleportasi ke §e${arguments[1]}§a, mohon tunggu konfirmasi.`,
      cmd_tpa_request_target: `§e${arguments[1]}§a mengirimkan permintaan teleportasi ke kamu. Gunakan §2/tpaaccept§a untuk menerima atau §c/tpadeny§a untuk menolak.`,
      cmd_tpa_inqeue: "§cPermintaan teleportasi sudah aktif, harap tunggu.",
      cmd_tpaaccept_description: "Terima permintaan teleportasi dari pemain lain",
      cmd_tpadeny_description: "Tolak permintaan teleportasi dari pemain lain",
      cmd_tpaaccept_success: `§e${arguments[1]} §atelah ditransportasi ke lokasimu.`,
      cmd_tpadeny_success: `§cPermintaan teleportasi dari §e${arguments[1]} §ctelah ditolak.`,
      cmd_tpa_notfound: "§cTidak ada permintaan teleportasi aktif.",
      cmd_tpa_expired: `§7Permintaan teleportasi ke §e${arguments[1]} §7kadaluarsa.`,
      cmd_topmoney_description: "Menampilkan daftar pemain dengan jumlah uang terbanyak",
      cmd_pay_description: "Transfer Uang ke player lain",
      cmd_pay_failed_enough: "§cKamu tidak memiliki cukup uang untuk diberikan",
      cmd_pay_failed_minimum: `§cMinimal Transfer adalah ${arguments[1]}Rp`,
      cmd_pay_success_sender: `§aBerhasil mengtransfer Uang §e${arguments[1]}Rp§a ke ${arguments[2]}`,
      cmd_pay_success_target: `§a${arguments[2]} telah mengtransfer Uang §e${arguments[1]}Rp`,
      cmd_invsee_description: "melihat inventaris pemain",
      cmd_land_description: "Perintah pengelolaan tanah",
      cmd_land_here_owner: `§aKamu berada di lahan milikmu sendiri. ID: §f${arguments[1]}`,
      cmd_land_here_not_owner: `§cLahan ini dimiliki oleh §f${arguments[1]}`,
      cmd_land_here_none: "§7Kamu tidak berada di dalam lahan manapun.",
      cmd_land_sell_missing: "§cTolong masukkan ID lahan yang ingin dihapus.",
      cmd_land_sell_notfound: `§cLahan dengan ID §f${arguments[1]} §ctidak ditemukan.`,
      cmd_land_sell_not_owner: `§cKamu bukan pemilik lahan ini.`,
      cmd_land_sell_success: `§aLahan dengan ID §f${arguments[1]} §aberhasil dijual.`,
      cmd_land_list_empty: "§7Kamu tidak memiliki lahan apapun.",
      cmd_land_create_pos1: `§ePosisi pertama ditetapkan di §7X: ${arguments[1]}, Z: ${arguments[2]}`,
      cmd_land_create_pos2: "§eKlik blok kedua untuk menetapkan posisi kedua.",
      cmd_land_create_toosmall: `§cLahan terlalu kecil. Minimum adalah §f${arguments[1]} blok.`,
      cmd_land_create_overlap: `§cPosisi ini Bertabrakan dengan lahan lain §7(ID: ${arguments[1]})`,
      cmd_land_create_nomoney: `§cUang tidak cukup. Dibutuhkan §f${arguments[1]}§c, kamu hanya punya §f${arguments[2]}`,
      cmd_land_create_success: "§aBerhasil membeli lahan!",
      cmd_land_create_success_id: `§aID Lahan: §f${arguments[1]} §a| Harga: §f${arguments[2]}`,
      cmd_land_create_cancel: "§cPembelian dibatalkan.",
      cmd_clearchat_description: "Membersihkan Chat yang menumpuk",
      cmd_clearchat_success: "§aBerhasil membersihkan Chat",
      cmd_scorehud_description: "Menyalakan atau Mematikan Scorehudmu",
      cmd_scorehud_enabled: "§7Scorehud §a[Dinyalakan]",
      cmd_scorehud_disabled: "§7Scorehud §c[Dimatikan]",
      cmd_setscorehud_description: "Mengatur isi Scorehud",
      cmd_setscorehud_message: "§eMemperbarui Isi Scorehud",
      cmd_ctitle_description: "Kirim Pesan Title Khusus",
      cmd_ranklist_description: "Lihat Semua Rank yang tersedia",
      cmd_csize_description: "Kostumisasi ukuran mu",
      cmd_csize_minimum: "Ukuran Minimum adalah 0.3",
      cmd_csize_maximum: "Ukuran Maximum adalah 10",
      cmd_rtp_description: "Berteleportasi secara acak",
      cmd_rtp_failed_reload: "§7Teleportasi acak §cGagal§7 karena server di §emuat ulang!",
      cmd_rtp_failed_leave: "§cTeleportasi secara acak tidak Valid karena kamu keluar!",
      cmd_gms_description: "Mengubah mode permainan menjadi survival",
      cmd_gms_message: "Merubah mode permainan mu menjadi §eSurvival",
      cmd_gmc_description: "Mengubah mode permainan menjadi creative",
      cmd_gmc_message: "Merubah mode permainan mu menjadi §bCreative",
      cmd_spectator_description: "Mengubah mode permainan menjadi spectator",
      cmd_spectator_message: "Merubah mode permainan mu menjadi §aSpectator",
      cmd_invis_description: "Membuat player menjadi tak terlihat",
      cmd_invis_message_remove: "Menghapus Efek tak terlihat",
      cmd_invis_message_add: "Menerapkan Efek tak terlihat",
      cmd_iditem_description: "Mengecek Id Item Mainhand",
      cmd_news_description: "Melihat Informasi Terbaru",
      cmd_clearrank_description: "Menghapus semua rank yang ada pada Player",
      cmd_clearrank_message: `§aMenghapus ${arguments[1]} dari §e${arguments[2]}`,
      cmd_daily_description: "Hadiah Harian",
cmd_daily_failed_notfound_message: `§cTidak ada hadiah untuk hari §e${arguments[1]}`,
cmd_daily_failed_cooldown_message: `§7Hadiah Harian untuk §e${arguments[1]}§7 masih dalam cooldown, bisa digunakan lagi pada §a${arguments[2]}`,
cmd_daily_success: `§aBerhasil mengambil Hadiah Harian §e${["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"][arguments[1]]}§a, bisa digunakan lagi pada §2${arguments[2]}`,
      cmd_weekly_description: "Hadiah Mingguan",
      cmd_weekly_failed_notfound_message: `§copsi §e${arguments[1]}§c tidak ditemukan di data`,
      cmd_weekly_failed_cooldown_message: `§7Hadiah Mingguan untuk §e${arguments[1]}§7 masih dalam cooldown, tunggu dapat digunakan pada §a${arguments[2]}`,
      cmd_weekly_success: `§aBerhasil mengambil Hadiah Mingguan §e${arguments[1]}§a dapat menggunakan lagi pada §2${arguments[2]}`,
      cmd_fly_description: "Terbang"
    };
  else if (arguments[0] === "en")
    return {
      select: "§aChanged language to English",
      command_cooldown: `§7Command '§f${arguments[1]}§7' in cooldown, wait ${arguments[2]}s.`,
      system_clear_countdown: `§6${arguments[1]} §fin ${arguments[2]}s`,
      system_clear_chat_success: `§6[ClearChat] §aSuccessfully clear the Chat`,
      system_clear_entities_success: `§6[ClearLag] §aSuccessfully removed ${arguments[1]} entities`,
      ui_ranklist_title: "§lRank - List",
      ui_ranklist_header1: "Official Ranks list",
      ui_ranklist_header2: "Wanna Buy?",
      ui_ranklist_label: "Contact Moderator or Admin this Server",
      ui_confirmation_title: "Confirmation",
      ui_confirmation_button_buy: "Buy",
      ui_confirmation_button_sell: "Sell",
      ui_confirmation_button_cancel: "Cancel",
      ui_confirmation_body_land_buy: `Size: ${arguments[1]} blocks\nPrice: $${arguments[2]}\nDo you want to buy this land?`,
      ui_confirmation_body_land_sell: `Size: ${arguments[2]} blocks\nPrice: $${arguments[3]}\nAre you sure to sell this land with ID ${arguments[1]}?`,
      event_break_land: `§cYou cannot break this land. Owned by §f${arguments[1]}`,
      event_place_land: `§cYou cannot place anything here. Owned by §f${arguments[1]}`,
      event_interact_land: `§cYou cannot interact here. Owned by §f${arguments[1]}`,
      event_farmland_land: `§cYou are in a farmland area. Owned by §f${arguments[1]}`,
      cmd_arg_empty: "§cPlease provide the required arguments.",
      player_undefined: "§cPlayer not found.",
      player_offline: "§7Player is offline.",
      player_dont_have_permission: "§cYou do not have permission to use this feature.",
      ui_close: "close",
      chat_message_cooldown: `Chat Cooldown, Wait ${arguments[1]}s`,
      cmd_lang_description: "Change ServerTool language",
      cmd_lang_notfound: `§cLanguage §4'${arguments[1]}'§c not found.`,
      cmd_help_title: `§aHELP (§r§l${arguments[1] || "All"}§r§a):\n§2`,
      cmd_help_description: "help commands",
      cmd_help_category_notfound: `§cCategory §4'${arguments[1]}'§c not found.`,
      cmd_tps_description: "See TPS",
      cmd_rules_description: "See Rules",
      cmd_plugin_description: "View installed plugins",
      cmd_plugin_notfound: `§cPlugin §4'${arguments[1]}'§c not found.`,
      cmd_back_description: "Teleport back to the coordinate you last died",
      cmd_back_failed_undefined: `§cBack Location not found`,
      cmd_back_message: "§7You have §cdied§7, type §e'/back'§7 back to the last location",
      cmd_back_success: "§aSuccessfully Back to the last location you died",
      cmd_about_description: "About Addon",
      cmd_money_description: `See your Money`,
      cmd_money_message: `Your Money: §a$${arguments[1]}`,
      cmd_setmoney_description: "Set a player's money amount",
      cmd_home_description: "Teleport to Home",
      cmd_home_failed_notfound: `§cNo home with name §e'${arguments[1]}'§c was found.`,
      cmd_home_success: `§asuccessfully teleported to a house with the name §e${arguments[1]}`,
      cmd_sethome_description: "Set a Home",
      cmd_sethome_failed_defined: `§cA home with the name §4'${arguments[1]}'§c already exists, please use a different name!`,
      cmd_sethome_failed_limit: `§cYou have reached the Limit for Creating Houses, Delete your house to reduce the limit.`,
      cmd_sethome_failed_minimum: `§cMinimum Home Name is §e${arguments[1]}§c and cannot be less than that!`,
      cmd_sethome_failed_maximum: `§cMaximum Home Name is §e${arguments[1]}§c and cannot be more than that!`,
      cmd_sethome_success: `§aSuccessfully created a house with the name §2'${arguments[1]}'§a now your remaining limit is §e${arguments[2]}`,
      cmd_delhome_description: "Deletes a home with the specified name",
      cmd_delhome_success: `§aHome §2'${arguments[1]}'§a has been successfully deleted.`,
      cmd_heal_description: "Make Health into Max",
      cmd_heal_message: "§aHeal++",
      cmd_feed_description: "Make Hunger Bar into Max",
      cmd_feed_message: "Feed++",
      cmd_tpa_description: "Send a teleport request to another player",
      cmd_tpa_request_sender: `§aSent a teleport request to §e${arguments[1]}§a, waiting for confirmation.`,
      cmd_tpa_request_target: `§e${arguments[1]}§a has sent you a teleport request. Use §2/tpaaccept§a to accept or §c/tpadeny§a to deny.`,
      cmd_tpa_inqeue: "§cYou already have a pending teleport request. Please wait.",
      cmd_tpaaccept_description: "Accept a teleport request from another player",
      cmd_tpadeny_description: "Deny a teleport request from another player",
      cmd_tpaaccept_success: `§e${arguments[1]} §ahas been teleported to your location.`,
      cmd_tpadeny_success: `§cTeleport request from §e${arguments[1]} §chas been denied.`,
      cmd_tpa_notfound: "§cNo active teleport request found.",
      cmd_tpa_expired: `§7Teleport request to §e${arguments[1]} §7has expired.`,
      cmd_topmoney_description: "Displays the list of players with the highest amount of money",
      cmd_pay_description: "Transfer Money to other players",
      cmd_pay_failed_enough: "§cYou don't have enough money to give",
      cmd_pay_failed_minimum: `§cMinimum Transfer is $${arguments[1]}`,
      cmd_pay_success_sender: `§aSuccessfully transferred Money §e$${arguments[1]}§a to ${arguments[2]}`,
      cmd_pay_success_target: `§a${arguments[2]} has transferred money §e$${arguments[1]}`,
      cmd_invsee_description: "see player Inventory",
      cmd_land_description: "Land management command",
      cmd_land_here_owner: `§aYou are in your own land. ID: §f${arguments[1]}`,
      cmd_land_here_not_owner: `§cThis land is owned by §f${arguments[1]}`,
      cmd_land_here_none: "§7You are not standing on any land.",
      cmd_land_sell_missing: "§cPlease specify the ID of the land to remove.",
      cmd_land_sell_notfound: `§cLand with ID §f${arguments[1]} §cnot found.`,
      cmd_land_sell_not_owner: `§cYou are not the owner of this land.`,
      cmd_land_sell_success: `§aSuccessfully sell land with ID §f${arguments[1]}.`,
      cmd_land_list_empty: "§7You do not own any land.",
      cmd_land_create_pos1: `§eFirst position set at §7X: ${arguments[1]}, Z: ${arguments[2]}`,
      cmd_land_create_pos2: "§eClick another block to set the second position.",
      cmd_land_create_toosmall: `§cLand too small. Minimum is §f${arguments[1]} blocks.`,
      cmd_land_create_overlap: `§cOverlaps with existing cmd_land §7(ID: ${arguments[1]})`,
      cmd_land_create_nomoney: `§cInsufficient funds. Required §f${arguments[1]}§c, but you only have §f${arguments[2]}`,
      cmd_land_create_success: "§aLand successfully purchased!",
      cmd_land_create_success_id: `§aLand ID: §f${arguments[1]} §a| Price: §f${arguments[2]}`,
      cmd_land_create_cancel: "§cPurchase canceled.",
      cmd_clearchat_description: "Cleaning chats that have accumulated",
      cmd_clearchat_success: "§aSuccessfully cleared Chat",
      cmd_scorehud_description: "Enable or Disable your Scorehud",
      cmd_scorehud_enabled: "§7Scorehud §a[ENABLED]",
      cmd_scorehud_disabled: "§7Scorehud §c[DISABLED]",
      cmd_setscorehud_description: "Setup or Setting Scorehud",
      cmd_setscorehud_message: "§eUpdate Scorehud Layout",
      cmd_ctitle_description: "Sent Custom Title Message",
      cmd_ranklist_description: "See all available Ranks",
      cmd_csize_description: "Customize your Size",
      cmd_csize_minimum: "Size minimum value is 0.3",
      cmd_csize_maximum: "Size maximum value is 10",
      cmd_rtp_description: "Randomly teleporting",
      cmd_rtp_failed_reload: "§7Random Teleport §cFailed§7 cause the server is §ereload!",
      cmd_rtp_failed_leave: "§cRandom Teleport Invalid Cause Leave the Game!",
      cmd_gms_description: "Change GameMode to Survival",
      cmd_gms_message: "Change your GammeMode to §eSurvival",
      cmd_gmc_description: "Change GameMode to Creative",
      cmd_gmc_message: "Change your GammeMode to §bCreative",
      cmd_spectator_description: "Change GameMode to Spectator",
      cmd_spectator_message: "Change your GammeMode to §aSpectator",
      cmd_invis_description: "Make player invisible",
      cmd_invis_message_remove: "Remove Invisibility Effect",
      cmd_invis_message_add: "Add Invisibility Effect",
      cmd_iditem_description: "See IdItem Mainhand",
      cmd_news_description: "See News",
      cmd_clearrank_description: "Clear all ranks Player",
      cmd_clearrank_message: `§aRemove ${arguments[1]} from §e${arguments[2]}`,
      cmd_daily_description: "Daily Reward",
cmd_daily_failed_notfound_message: `§cNo reward found for §e${arguments[1]}`,
cmd_daily_failed_cooldown_message: `§7Daily Reward for §e${arguments[1]}§7 still in cooldown, available again on §a${arguments[2]}`,
cmd_daily_success: `§aSuccessfully claimed Daily Reward for §e${["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"][arguments[1]]}§a, available again on §2${arguments[2]}`,

      cmd_weekly_description: "Weekly Reward",
      cmd_weekly_failed_notfound_message: `§coption §e${arguments[1]}§c not found in data`,
      cmd_weekly_failed_cooldown_message: `§7Weekly Reward for §e${arguments[1]}§7 is still on cooldown, wait can be used on §a${arguments[2]}`,
      cmd_weekly_success: `§aSuccessfully took the Weekly Prize §e${arguments[1]}§a can use it again in §2${arguments[2]}`,
      cmd_fly_description: "Fly"
    };
}
